version: '3'
services:
  dbt-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - dbt-server
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  mongodb: