version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true